<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="utf-8">
	<title>Blog - Connexion Admin</title>
	<link href="https://fonts.googleapis.com/css?family=Overlock" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/styleLogin.css">
</head>
<body>
	<header>
	</header>
	<main>
		<form action="login.php" method="POST">
			<h1>Login to your account</h1>
			<p><input type="text" name="username" placeholder="Username"></p>
			<p><input type="password" name="password" class="password" placeholder="Password"></p>
			<p><input type="checkbox" id="showHide"> Show Password ?</p>
			<input type="submit" name="submit" value="Login">
			<?php if($error!=''): ?>
	            <div class="alert" role="alert" style="color: red; text-transform: uppercase;"><?=$error?></div>
	        <?php endif; ?>
		</form>
	</main>
	<footer>
	</footer>
    <script src="js/script.js"></script>
</body>
</html>