<main class="main">
        <section>
            <nav>
                <a href="admin.php">Home</a>
                <a href="add.php">New article</a>
                <a href="users.php">Users</a>
                <a href="newUser.php">New user</a>
                <a href="categories.php">Categories</a>
                <a href="new_category.php">New category</a>
           </nav>
        </section>