<!DOCTYPE html>
<html lang="fr-FR">
<head>
    <meta charset="utf-8">
    <title>Blog - New user</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
    <link href="https://fonts.googleapis.com/css?family=Overlock" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/styleAdmin.css">
</head>
<body>
    <header>
        <a href="../index.php" target="_blank">Go to Blog</a>
        <h1>Welcome to your admin tool</h1>
        <a href="deconnexion.php" onclick="return logout();">Logout</a>
    </header>
    <main class="main">
        <section>
            <nav>
                <a href="admin.php">Home</a>
                <a href="add.php">New article</a>
                <a href="users.php">Users</a>
                <a href="newUser.php">New user</a>
                <a href="categories.php">Categories</a>
                <a href="new_category.php">New category</a>
            </nav>
        </section>
        <section>
            <h2>New user</h2>
            <p><?=$erreur?></p>
            <form action="newUser.php" method="POST" enctype="multipart/form-data">
                <ul>
                    <li>
                        <label>Username</label>
                        <input type="text" name="username">
                    </li>
                    <li>
                        <label>Password</label>
                        <input type="password" name="password">
                    </li>
                    <li>
                        <label>Name</label>
                        <input type="text" name="nom">
                    </li>
                    <li>
                        <label>Last Name</label>
                        <input type="text" name="prenom">
                    </li>
                    <li>
                        <label>Email</label>
                        <input type="text" name="email">
                    </li>
                </ul>
                <input type="submit" name="submit" value="Send">
            </form>
        </section>
    </main>
    <footer>

    </footer>
</body>
</html>