	<main>
		<article class="about">
			<img src="img/portrait.jpg" alt="Yannick Rabo" id="yannick">
			<p>I'm Yannick, and welcome to my Blog.</p>
			<p>I started this blog as a project during my formation as a Web Developper.</p>
			<p>I decided to keep it going to experiment on, and grow it.</p>
			<p>I write articles about all the things I like. From movies to games, music, global news in my life etc. I have real fun doing this, even if for now there are no daily articles, but that might change in the future.</p>
			<p>I hope you enjoy it here, and if you want you can always contact me to give ideas, or if there are things that can get better around here.</p>
		</article>
	</main>