	<main class="article">
    	<article>
            <h2><?= $article['titre'] ?></h2>
            <h3><?= $article['subtitle'] ?></h3>
            <h4><?= $article['titreCategorie'] ?></h4>
            <div class="content">
                <?= $article['contenu'] ?>
            </div>
            <?php if(empty($article['imgUne'])) { ?>
                <img src="admin/uploads/noimage.jpg" alt="no image">
            <?php } else { ?>
                <img src="admin/uploads/<?= $article['imgUne']; ?>" alt="<?= $article['imgUne']; ?>">
            <?php } ?>
            <p class="date"><?= $users['userName']; ?> | <?= $article['datePublication'] ?></p>
            <p class="tags">TAGS: <span><?= $article['motsClefs'] ?></span></p>
        </article>
        <section id="comments" class="comment">
        	<h3>Comments</h3>
        	<form action="comm.php" method="POST">
        		<input type="hidden" name="id" value="<?=$idArticle?>" />
                <label>Name</label>
                <input type="text" name="name" required>
                <label>Comment</label>
                <textarea name="comment"  placeholder="Leave your comment here ..." required></textarea>
                <input type="submit" name="submit" value="Post">
            </form>
            <?php foreach($comments as $comment): ?>
                <article>
                    <p><span><?= $comment['pseudo'] ?></span>   <?= $comment['comm_date'] ?></p>
                    <p><?= $comment['texte'] ?></p>
                </article>
            <?php endforeach; ?>
        </section>
	</main>