<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119501792-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-119501792-1');
	</script>
	<meta charset="utf-8">
	<meta name="description" content="A place where you'll find out more about me. News, movies, games etc. Where I talk about what I like and what makes me happy. What games I play, and my thoughts about them, same goes for movies. Things I try out and much more.">
	<meta name="keywords" content="ynkrabo, blog, movies, games, video, news,">
	<meta name="google-site-verification" content="J4HFc9cgdwUGMx1a7sqxmC2gApNhABkjG3n9oHaMw4c" />
	<title><?= $pagetitle ?></title>
    <base href="https://blog.ynkrabo.fr">
    <link rel="icon" type="img/ico" href="img/favicon.ico">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Pathway+Gothic+One" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
	<header>
		<div id="progress" class="progress-container">
			<div class="progress-bar" id="myBar"></div>
		</div>
		<nav>
			<section>
				<a href="homepage"><img src="img/logoynkrabo.png" alt="logo YNKRabo"></a>
			</section>
			<section  class="menu">
				<ul>
					<li>Categories
						<ul class="submenu">
							<li><a href="categories/1/news">News</a></li>
							<li><a href="categories/2/movies">Movies</a></li>
							<li><a href="categories/3/video-games">Video Games</a></li>
							<li><a href="categories/4/science">Science</a></li>
						</ul>
					</li>
					<li><a href="contact">Contact</a></li>
					<li><a href="about">About</a></li>
				</ul>
			</section>
			<section>
				<form action="search" method="POST">
					<input type="text" name="search" placeholder="Search...">
				</form>
			</section>
		</nav>
	</header>